spring.application.name=backend

management.endpoints.web.exposure.include=health,info,prometheus

spring.datasource.url=
spring.datasource.driver-class-name=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=

# JWT
jwt.secret=
jwt.access-token-expiry=1800000
jwt.refresh-token-expiry=604800000