spring.application.name=backend

# DataSource
spring.datasource.url=
spring.datasource.driver-class-name=
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=

# JWT
jwt.secret=
jwt.access-token-expiry=
jwt.refresh-token-expiry=

# CORS
cors.allowed-origins=

management.endpoints.web.exposure.include=health,info,prometheus